In [15]:
import numpy as np
import pandas as pd
mydata = pd.read_csv('Fremont_weather.txt')
df = pd.read_csv('Admission_Predict_Ver1.1.csv')
# print(mydata.shape)
# print(mydata)
# print(df)
print(df.head()) # This will print first five data points, if you put some number in e.g. head(6) it will print 6 data sets

print(df.tail()) # This will print lasr five data points, if you put some number in e.g. tail(6) it will print 6 data sets





   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1        337          118                  4  4.5  4.5  9.65   
1           2        324          107                  4  4.0  4.5  8.87   
2           3        316          104                  3  3.0  3.5  8.00   
3           4        322          110                  3  3.5  2.5  8.67   
4           5        314          103                  2  2.0  3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65  
     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
495         496        332          108                  5  4.5  4.0  9.02   
496         497        337          117                  5  5.0  5.0  9.87   
497         498        330          120                  5  4.5  5.0  9.56   
498         499        312          103

In [33]:
# print(df)
def header(msg):
    print('[ ' + msg + ' ]')
    print('==' * 60)
    
header('We have the data above for admission')
df.info() 


[ We have the data above for admission ]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 9 columns):
Serial No.           500 non-null int64
GRE Score            500 non-null int64
TOEFL Score          500 non-null int64
University Rating    500 non-null int64
SOP                  500 non-null float64
LOR                  500 non-null float64
CGPA                 500 non-null float64
Research             500 non-null int64
Chance of Admit      500 non-null float64
dtypes: float64(4), int64(5)
memory usage: 35.2 KB


In [34]:
header("4. df.dtypes")
print(df.dtypes)
header("4. df.index")
print(df.index)

header("4. df.columns")
print(df.columns)

header("4. df.values")
print(df.values)

header("All the data")
print(df)

[ 4. df.dtypes ]
Serial No.             int64
GRE Score              int64
TOEFL Score            int64
University Rating      int64
SOP                  float64
LOR                  float64
CGPA                 float64
Research               int64
Chance of Admit      float64
dtype: object
[ 4. df.index ]
RangeIndex(start=0, stop=500, step=1)
[ 4. df.columns ]
Index(['Serial No.', 'GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
       'LOR', 'CGPA', 'Research', 'Chance of Admit '],
      dtype='object')
[ 4. df.values ]
[[  1.   337.   118.   ...   9.65   1.     0.92]
 [  2.   324.   107.   ...   8.87   1.     0.76]
 [  3.   316.   104.   ...   8.     1.     0.72]
 ...
 [498.   330.   120.   ...   9.56   1.     0.93]
 [499.   312.   103.   ...   8.43   0.     0.73]
 [500.   327.   113.   ...   9.04   0.     0.84]]
[ All the data ]
     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1        337          118                  4  4.5  4.5  

In [36]:
# 5. statistical summary of each column
header("5. df.describe()")
print(df.describe())


[ 5. df.describe() ]
       Serial No.   GRE Score  TOEFL Score  University Rating         SOP  \
count  500.000000  500.000000   500.000000         500.000000  500.000000   
mean   250.500000  316.472000   107.192000           3.114000    3.374000   
std    144.481833   11.295148     6.081868           1.143512    0.991004   
min      1.000000  290.000000    92.000000           1.000000    1.000000   
25%    125.750000  308.000000   103.000000           2.000000    2.500000   
50%    250.500000  317.000000   107.000000           3.000000    3.500000   
75%    375.250000  325.000000   112.000000           4.000000    4.000000   
max    500.000000  340.000000   120.000000           5.000000    5.000000   

             LOR        CGPA    Research  Chance of Admit   
count  500.00000  500.000000  500.000000         500.00000  
mean     3.48400    8.576440    0.560000           0.72174  
std      0.92545    0.604813    0.496884           0.14114  
min      1.00000    6.800000    0.000000 

In [55]:
# print(df)
x= df.head(10)
print(x)
# 7. slicing records
header("7. slicing -- Research ")
print(x.Research )

header("7. slicing -- df['Research ']")
print(x['University Rating'])

header("7. slicing -- df[2:4]")            # index with single column
print(x[2:4])    

   Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0           1        337          118                  4  4.5  4.5  9.65   
1           2        324          107                  4  4.0  4.5  8.87   
2           3        316          104                  3  3.0  3.5  8.00   
3           4        322          110                  3  3.5  2.5  8.67   
4           5        314          103                  2  2.0  3.0  8.21   
5           6        330          115                  5  4.5  3.0  9.34   
6           7        321          109                  3  3.0  4.0  8.20   
7           8        308          101                  2  3.0  4.0  7.90   
8           9        302          102                  1  2.0  1.5  8.00   
9          10        323          108                  3  3.5  3.0  8.60   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4  

In [58]:
print(x[['Research','GRE Score']])

   Research  GRE Score
0         1        337
1         1        324
2         1        316
3         1        322
4         0        314
5         1        330
6         1        321
7         0        308
8         0        302
9         0        323


In [67]:
header("7. slicing -- df.loc[:,['GRE Score','CGPA']]")
print(x.loc[:,['GRE Score','CGPA']])         # multiple columns: df.loc[from_row:to_row,['GRE Score','CGPA']]

[ 7. slicing -- df.loc[:,['GRE Score','CGPA']] ]
   GRE Score  CGPA
0        337  9.65
1        324  8.87
2        316  8.00
3        322  8.67
4        314  8.21
5        330  9.34
6        321  8.20
7        308  7.90
8        302  8.00
9        323  8.60


In [75]:
#This will print the single value
header(" slicing scalar value -- df.loc[9,['CGPA']]")
print(x.loc[9,['CGPA']])

[  slicing scalar value -- df.loc[9,['CGPA']] ]
CGPA    8.6
Name: 9, dtype: float64


In [74]:

header(" x.iloc[3:5,[0,2]]")            # index location can receive range or list of indices
print(x.iloc[3:5,[0,2]])

[  x.iloc[3:5,[0,2]] ]
   Serial No.  TOEFL Score
3           4          110
4           5          103
